### ISSUE TITLE
如何定时每日执行

### ISSUE THREAD

**Issue by nameryan** [9ft/BingWallpaper#2]
请问如何设置定时每日执行？ 对cron命令不太熟悉的情况。

**Comment by mzcinf** [comment]
把 `BingWallpaper.cron` 文件中 .sh 的路径改好，然后执行 `crontab BingWallpaper.cron` 即可

**Comment by fhdone** [comment]
cron文件每小时跑因该是  0 */1 * * *

**Comment by mzcinf** [comment]
> cron文件每小时跑因该是 0 */1 * * *

按需修改 😄
